security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            custom_authenticators:
                - App\Security\LoginAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    # Define access control rules for different paths
    # access_control:
    #     # Allow anonymous access to the login page
    #     - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     # Allow anonymous access to the root route
    #     - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     # Restrict access to paths starting with /admin to users with ROLE_ADMIN
    #     - { path: ^/admin, roles: ROLE_ADMIN }