parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    photos_directory_web: '/uploads/photos/'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_TOKEN)%'
    twilio_from: '%env(TWILIO_FROM)%'
    profile_photos_directory: '%kernel.project_dir%/public/uploads/profiles'
    gym_images_directory: '%kernel.project_dir%/public/uploads/gyms'
    STRIPE_PUBLIC_KEY: '%env(STRIPE_PUBLIC_KEY)%'
    STRIPE_SECRET_KEY: '%env(STRIPE_SECRET_KEY)%'

services:
    App\Service\SmsNotifier:
        arguments:
            $sid: '%twilio_sid%'
            $token: '%twilio_token%'
            $from: '%twilio_from%'
           
   
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $sid: '%twilio_sid%'
            string $token: '%twilio_token%'
            string $from: '%twilio_from%'
        

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Migrations/'

    App\Repository\NotificationRepository:
        autowire: true

    App\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']
